// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP54Qiap4suvBdRm9Tckwb2I_ycEED7o4',
    appId: '1:64977446608:web:a9eb515fae1dd90a1020d5',
    messagingSenderId: '64977446608',
    projectId: 'taskmanapp-f6c68',
    authDomain: 'taskmanapp-f6c68.firebaseapp.com',
    storageBucket: 'taskmanapp-f6c68.firebasestorage.app',
    measurementId: 'G-Y60Z1RV2TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvE5blVxPuCf_IDeFpkiqgCo7uDuPhhnE',
    appId: '1:64977446608:android:bae55f11f93044741020d5',
    messagingSenderId: '64977446608',
    projectId: 'taskmanapp-f6c68',
    storageBucket: 'taskmanapp-f6c68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8T8Aq6aiera8G1N6MfSlW3sV3WQB9AGg',
    appId: '1:64977446608:ios:23cd0189817ff16c1020d5',
    messagingSenderId: '64977446608',
    projectId: 'taskmanapp-f6c68',
    storageBucket: 'taskmanapp-f6c68.firebasestorage.app',
    iosBundleId: 'com.example.taskmanapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8T8Aq6aiera8G1N6MfSlW3sV3WQB9AGg',
    appId: '1:64977446608:ios:23cd0189817ff16c1020d5',
    messagingSenderId: '64977446608',
    projectId: 'taskmanapp-f6c68',
    storageBucket: 'taskmanapp-f6c68.firebasestorage.app',
    iosBundleId: 'com.example.taskmanapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP54Qiap4suvBdRm9Tckwb2I_ycEED7o4',
    appId: '1:64977446608:web:f3f4def25ec5d1ab1020d5',
    messagingSenderId: '64977446608',
    projectId: 'taskmanapp-f6c68',
    authDomain: 'taskmanapp-f6c68.firebaseapp.com',
    storageBucket: 'taskmanapp-f6c68.firebasestorage.app',
    measurementId: 'G-T816S1K2PR',
  );

}